sources:
  - name: SOAPDemo
    handler:
      soap:
        wsdl: https://www.crcind.com/csp/samples/SOAP.Demo.cls?WSDL
        selectQueryOperationsAuto: true

documents:
  - ./operations/*.graphql
